[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "runtoolsio-taro"
authors = [{name = "Stan Svec", email = "dev@stansvec.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
requires-python = ">=3.10"
dynamic = ["version", "description"]
dependencies = [
#    "runtoolsio-runcore @ git+ssh://git@github.com/runtoolsio/runcore",
    "pypager >=3.0.0",
]

[project.optional-dependencies]
test = ["pytest"]

[tool.flit.module]
name = "runtoolsio.taro"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src"

[project.urls]
Home = "https://github.com/runtoolsio/taro"
